"""add task concurrency control fields

Revision ID: 7e0f82396e0d
Revises: 9d40975b6851
Create Date: 2026-07-25 02:36:32.549765

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0f82396e0d'
down_revision: Union[str, None] = '9d40975b6851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 为现有任务行设置初始 version=0，避免 NOT NULL 约束失败
    op.add_column('config_tasks', sa.Column('version', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('config_tasks', sa.Column('execution_token', sa.String(length=100), nullable=True))
    op.add_column('config_tasks', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('config_tasks', sa.Column('locked_by', sa.String(length=100), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config_tasks', 'locked_by')
    op.drop_column('config_tasks', 'locked_at')
    op.drop_column('config_tasks', 'execution_token')
    op.drop_column('config_tasks', 'version')
    # ### end Alembic commands ###
